#!/usr/bin/python
import xmlrpclib
import urllib2
import urllib
from xml.etree import ElementTree
import xml.etree.ElementTree as ET
import logging
import requests
import subprocess
import sys
from socket import gethostname
from requests.auth import HTTPBasicAuth

def get_average_ping(ip):
	ping = subprocess.Popen(["fping", "-c", "3", ip], stdout=subprocess.PIPE)
	out = ping.communicate() 
	avg_ping = out[0][35:37]
	
	return str(avg_ping)