#!/usr/bin/python
from ConfigParser import SafeConfigParser
import xmlrpclib
import urllib2
import urllib
from xml.etree import ElementTree
import xml.etree.ElementTree as ET
import logging
import requests
import subprocess
import sys
from socket import gethostname
from requests.auth import HTTPBasicAuth
from ConfigParser import SafeConfigParser
import time

parser = SafeConfigParser()

try:
   parser.read("/usr/local/etc/influxdb.conf")
   host = parser.get("db", "host")
   database = parser.get("db", "database")
   username = parser.get("auth", "username")
   password = parser.get("auth", "password")
   instance = parser.get("cloud","instance")
except:
   print "Unable to read from config file"
   sys.exit(1)

influx_url = "http://"+host+"/write?db="+database

def send_to_influxdb(value, data_title, ip, template_id, template_name):
	print time.ctime() + ": Sending to influxdb..."
	request = requests.post(influx_url, data_title + ",ip=" + ip + ",template_id=" + str(template_id) + ",template_name=" + template_name + " value=" + value, auth=(username,password))
