#!/usr/bin/python
from ConfigParser import SafeConfigParser
import xmlrpclib
import urllib2
import urllib
from xml.etree import ElementTree
import xml.etree.ElementTree as ET
import logging
import requests
import subprocess
import sys
from socket import gethostname
from requests.auth import HTTPBasicAuth
from ConfigParser import SafeConfigParser
import time

def ssh_touch(ip):
	print time.ctime() + ": SSHing..."
	start = time.time()
	command = subprocess.call(["ssh", "testgroup@" + str(ip), "touch", "testfile"])
	elapsed = str(time.time() - start)[0:4]

	return elapsed